eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8083
spring:
  application:
    name: doctors-management